DROP TABLE IF EXISTS ewm_user CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS participation_request CASCADE;
DROP TABLE IF EXISTS compilation_event CASCADE;

CREATE TABLE IF NOT EXISTS ewm_user
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(300)                            NOT NULL,
    email VARCHAR(500)                            NOT NULL,
    CONSTRAINT pk_ewm_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) UNIQUE                      NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR(120)                            NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    category_id           BIGINT                                  NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator_id          BIGINT                                  NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    title              VARCHAR(120)                            NOT NULL,
    description        VARCHAR(7000),
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    participant_limit  INT,
    request_moderation BOOLEAN,
    views              INT,
    state_action       VARCHAR(50),
    state              VARCHAR(50),
    lat                FLOAT                                   NOT NULL,
    lon                FLOAT                                   NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_to_initiator FOREIGN KEY (initiator_id) REFERENCES ewm_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_to_category FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS participation_request
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    status    VARCHAR(50),
    CONSTRAINT pk_participation_request PRIMARY KEY (id),
    CONSTRAINT fk_participation_request_to_event FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE,
    CONSTRAINT fk_participation_request_to_ewm_user FOREIGN KEY (requester_id) REFERENCES ewm_user (id) ON DELETE CASCADE,
    UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilation_event
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    compilation_id BIGINT                                  NOT NULL,
    event_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_compilation_event PRIMARY KEY (id),
    CONSTRAINT fk_compilation_event_to_compilation FOREIGN KEY (compilation_id) REFERENCES compilation (id) ON DELETE CASCADE,
    CONSTRAINT fk_compilation_event_to_event FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE
);