DROP TABLE IF EXISTS endpoint_hit CASCADE;
DROP TABLE IF EXISTS view_stats CASCADE;

CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(300)                            NOT NULL,
    uri       VARCHAR(500)                            NOT NULL,
    ip        VARCHAR(50)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS view_stats
(
    app  VARCHAR(300) NOT NULL,
    uri  VARCHAR(500) NOT NULL,
    hits INTEGER      NOT NULL
);




